name: Epic Free Games Checker

on:
  schedule:
    - cron: "0 13 1-31/3 * *"   # every 3rd day at 13:00 UTC (adjust as you like)
  workflow_dispatch:            # allow manual runs from the Actions tab

jobs:
  run-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run checker
        env:
          EPIC_LOCALE: "en-US"
          EPIC_COUNTRY: "US"
          TIMEZONE: "America/Toronto"
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        run: |
          python your_script.py
